### ISSUE TITLE
Import fails using Unity 5.2.2f1

### ISSUE THREAD

**Issue by BouncingBit** [Dharengo/Spriter2UnityDX#4]
Hello,
I tried to import a simple character spriter project with one animation in it into Unity 5.2.2f1. However the asset import is looping forever and I have to forceably close Unity to be able to use it again. After a restart there's no Animator created.
I'm using Spriter Pro 4.1 for editing.

**Comment by Dharengo** [comment]
I am assuming that there's something about your .scml file that the importer does not agree with. It's very much a work in progress and errors are to be expected, sadly.

Have you tried importing one of the example files?

**Comment by BouncingBit** [comment]
Thank you for the quick answer. I've just tried the "MegaEnemies" example. The effect is the same. That is the loading progress bar appears ("Importing Assets"). Then the program seems to loop over the png files again and again.

**Comment by Dharengo** [comment]
I think I've run into someone with this issue before. Can you check something out for me?

Before importing the .scml file, import all the graphics, and make sure all the graphics files are imported as Sprite, then try importing the .scml file again.

**Comment by BouncingBit** [comment]
Okay. I did what you proposed:
1. Imported all png files
2. Manually "converted" them all to "Sprites" 
3. Then dragged&dropped the scml file into the Assets folder.

The import now works. However the z-Order seems to be screwed up. Anyway, thank you so far. (Maybe I did something wrong within spriter itself as I'm new to the topic...  :)

**Comment by Dharengo** [comment]
If the Z order is messed up only in play mode, try ticking the "Apply Spriter Z Order" box on the EntityRenderer
